import { Router } from 'express'
import { Prisma } from '@prisma/client'
import { prisma } from '../lib/prisma.js'
import { asyncHandler, badRequest, createdResponse, notFound, ok, requireAuth } from '../lib/http.js'
import { validate, z, money, idParam } from '../lib/validate.js'
import { findOpenRegister } from '../services/cashService.js'

const router=Router(); const dec=(v:number)=>new Prisma.Decimal(v.toFixed(2)); const round=(v:number)=>Math.round(v*100)/100
const day=(value?:string)=>{const d=value?new Date(`${value}T12:00:00`):new Date();d.setHours(0,0,0,0);return d}

router.get('/overview',validate({query:z.object({date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional()})}),asyncHandler(async(req,res)=>{
  const {tenantId}=requireAuth(req);const selected=day(String(req.query.date||'' )||undefined);const end=new Date(selected);end.setDate(end.getDate()+1);const start30=new Date(selected);start30.setDate(start30.getDate()-29)
  const [register,entries,payments,payables,receivables,channels]=await Promise.all([
    findOpenRegister(prisma,tenantId),
    prisma.cashEntry.findMany({where:{cashRegister:{tenantId},createdAt:{gte:start30,lt:end}},include:{createdBy:{select:{firstName:true,lastName:true}},cashRegister:{select:{openedAt:true}}},orderBy:{createdAt:'desc'}}),
    prisma.orderPayment.findMany({where:{order:{tenantId,createdAt:{gte:start30,lt:end},status:{not:'cancelled'}}},include:{order:{select:{createdAt:true,orderNumber:true,salesChannel:{select:{name:true,slug:true}}}}}}),
    prisma.accountPayable.findMany({where:{tenantId},select:{amount:true,amountPaid:true,dueDate:true}}),
    prisma.accountReceivable.findMany({where:{tenantId},include:{customer:{select:{name:true}},order:{select:{orderNumber:true}}},orderBy:{dueDate:'asc'}}),
    prisma.salesChannel.findMany({where:{tenantId},select:{id:true,name:true,slug:true,platformFeePerc:true,platformFeeFixed:true}})
  ])
  const selectedEntries=entries.filter(e=>e.createdAt>=selected);const inflows=selectedEntries.filter(e=>['sale','supply'].includes(e.type)).reduce((s,e)=>s+Number(e.amount),0);const outflows=selectedEntries.filter(e=>['withdrawal','expense','refund'].includes(e.type)).reduce((s,e)=>s+Number(e.amount),0)
  const openPayables=payables.filter(p=>Number(p.amountPaid)<Number(p.amount));const openReceivables=receivables.filter(r=>Number(r.amountReceived)<Number(r.amount));const receivableTotal=openReceivables.reduce((s,r)=>s+Number(r.amount)-Number(r.amountReceived),0)
  const daily=Array.from({length:30},(_,i)=>{const d=new Date(start30);d.setDate(d.getDate()+i);const next=new Date(d);next.setDate(next.getDate()+1);return{date:d.toISOString().slice(0,10),entries:round(entries.filter(e=>e.createdAt>=d&&e.createdAt<next&&['sale','supply'].includes(e.type)).reduce((s,e)=>s+Number(e.amount),0)),exits:round(entries.filter(e=>e.createdAt>=d&&e.createdAt<next&&['withdrawal','expense','refund'].includes(e.type)).reduce((s,e)=>s+Number(e.amount),0))}})
  const byMethod:Record<string,number>={};for(const p of payments.filter(p=>p.order.createdAt>=selected))byMethod[p.method]=round((byMethod[p.method]||0)+Number(p.amount))
  const byChannel=new Map<string,{name:string;gross:number;fee:number;orders:Set<string>}>();for(const p of payments.filter(p=>p.order.createdAt>=selected)){const name=p.order.salesChannel?.name||'Loja própria';const slug=p.order.salesChannel?.slug||'loja-propria';const cfg=channels.find(c=>c.slug===slug);const row=byChannel.get(slug)||{name,gross:0,fee:0,orders:new Set<string>()};row.gross+=Number(p.amount);row.orders.add(p.order.orderNumber);row.fee+=Number(p.amount)*Number(cfg?.platformFeePerc||0)/100;byChannel.set(slug,row)}
  return ok(res,{date:selected.toISOString().slice(0,10),cashRegister:register?{id:register.id,openedAt:register.openedAt}:null,summary:{balance:round(inflows-outflows),inflows:round(inflows),outflows:round(outflows),receivable:round(receivableTotal),payable:round(openPayables.reduce((s,p)=>s+Number(p.amount)-Number(p.amountPaid),0))},daily,byMethod:Object.entries(byMethod).map(([method,amount])=>({method,amount})),movements:selectedEntries.slice(0,20),channels:[...byChannel.entries()].map(([slug,r])=>({slug,name:r.name,gross:round(r.gross),fee:round(r.fee),net:round(r.gross-r.fee),orders:r.orders.size})),receivables:openReceivables.slice(0,10).map(r=>({...r,remaining:round(Number(r.amount)-Number(r.amountReceived))}))})
}))

const create=z.object({description:z.string().trim().min(2).max(200),customerId:z.string().nullish(),amount:money.refine(v=>v>0),dueDate:z.coerce.date(),installments:z.coerce.number().int().min(1).max(60).default(1),notes:z.string().trim().max(500).nullish()})
router.post('/receivables',validate({body:create}),asyncHandler(async(req,res)=>{const {tenantId}=requireAuth(req);const b=req.body as z.infer<typeof create>;if(b.customerId&&!await prisma.customer.findFirst({where:{id:b.customerId,tenantId}}))throw badRequest('Cliente não encontrado.');const per=round(b.amount/b.installments);const rows=await prisma.$transaction(Array.from({length:b.installments},(_,i)=>{const due=new Date(b.dueDate);due.setMonth(due.getMonth()+i);const value=i===b.installments-1?round(b.amount-per*(b.installments-1)):per;return prisma.accountReceivable.create({data:{tenantId,customerId:b.customerId||null,description:b.installments>1?`${b.description} (${i+1}/${b.installments})`:b.description,amount:dec(value),dueDate:due,installment:i+1,installments:b.installments,notes:b.notes||null}})}));return createdResponse(res,rows)}))
router.post('/receivables/:id/receive',validate({params:idParam,body:z.object({amount:money.refine(v=>v>0),paymentMethod:z.enum(['cash','pix','credit','debit','transfer'])})}),asyncHandler(async(req,res)=>{const {tenantId,userId}=requireAuth(req);const id=String(req.params.id);const row=await prisma.accountReceivable.findFirst({where:{id,tenantId}});if(!row)throw notFound('Conta a receber não encontrada.');const b=req.body as {amount:number;paymentMethod:string};const remaining=round(Number(row.amount)-Number(row.amountReceived));if(b.amount>remaining+.001)throw badRequest('O recebimento é maior que o saldo da conta.');const next=round(Number(row.amountReceived)+b.amount);const result=await prisma.$transaction(async tx=>{const updated=await tx.accountReceivable.update({where:{id},data:{amountReceived:dec(next),paymentMethod:b.paymentMethod,receivedAt:next>=Number(row.amount)?new Date():null}});if(b.paymentMethod==='cash'){const register=await findOpenRegister(tx,tenantId);if(!register)throw badRequest('Abra o caixa antes de receber em dinheiro.');await tx.cashEntry.create({data:{cashRegisterId:register.id,type:'sale',amount:dec(b.amount),description:`Recebimento: ${row.description}`,paymentMethod:'cash',referenceType:'receivable',referenceId:id,createdById:userId}})}return updated});return ok(res,result)}))
export default router
