import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { Cake, CheckCircle2, ChevronRight, Coins, Edit3, Gift, Heart, Loader2, MapPin, Phone, Search, ShoppingBag, Sparkles, TicketPercent, UserPlus, Users, X } from 'lucide-react'

import { useAuth } from '../context/AuthContext'
import { apiGet, apiPost, apiPut, errorMessage } from '../lib/api'

type Segment = 'all' | 'champions' | 'loyal' | 'new' | 'risk' | 'inactive' | 'regular'
interface Customer { id: string; name: string; phone: string; email?: string | null; address?: string | null; neighborhood?: string | null; city?: string | null; state?: string | null; zipCode?: string | null; notes?: string | null; birthday?: string | null; marketingConsent: boolean; ltv: number | string; totalOrders: number; lastOrderAt?: string | null; loyaltyPoints: number; cashbackBalance: number | string; segment: Segment; createdAt: string }
interface Summary { total: number; active: number; averageTicket: number; recurrence: number; cashbackOutstanding: number; segmentCounts: Record<string, number> }
interface CustomerDetail extends Customer { addresses:Array<{id:string;label:string;address:string;neighborhood:string;city?:string|null;state?:string|null;zipCode?:string|null;isDefault:boolean}>; orders: Array<{ id: string; orderNumber: string; status: string; totalAmount: number | string; createdAt: string }>; loyaltyTransactions: Array<{ id: string; pointsDelta: number; cashbackDelta: number | string; pointsBalance: number; cashbackBalance: number | string; reason: string; createdAt: string }> }
interface Coupon { id:string; code:string; description?:string|null; discountType:'percentage'|'fixed'; discountValue:number|string; minimumOrder:number|string; maximumDiscount?:number|string|null; startsAt:string; endsAt?:string|null; usageLimit?:number|null; usageLimitPerCustomer:number; usageCount:number; active:boolean }

const emptyForm = { name: '', phone: '', email: '', address: '', neighborhood: '', city: '', state: '', zipCode: '', notes: '', birthday: '', marketingConsent: false }
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })
const fieldClass = 'h-11 w-full rounded-lg border border-line bg-canvas px-3 text-sm text-ink outline-none focus:border-brand'
const labels: Record<Segment, string> = { all: 'Todos', champions: 'Campeões', loyal: 'Fiéis', new: 'Novos', risk: 'Em risco', inactive: 'Inativos', regular: 'Regulares' }
const tones: Record<Segment, string> = { all: '', champions: 'bg-brand-soft text-accent', loyal: 'bg-blue-50 text-blue-700', new: 'bg-good-soft text-good', risk: 'bg-warn-soft text-warn', inactive: 'bg-slate/10 text-slate', regular: 'bg-canvas text-slate' }

export default function CustomersPage() {
  const { can } = useAuth(); const canManage = can('customers:manage')
  const [customers, setCustomers] = useState<Customer[]>([]); const [summary, setSummary] = useState<Summary | null>(null)
  const [selected, setSelected] = useState<CustomerDetail | null>(null); const [search, setSearch] = useState(''); const [segment, setSegment] = useState<Segment>('all')
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const [showForm, setShowForm] = useState(false); const [editing, setEditing] = useState<Customer | null>(null); const [form, setForm] = useState(emptyForm)
  const [showBenefit, setShowBenefit] = useState(false); const [benefit, setBenefit] = useState({ pointsDelta: '', cashbackDelta: '', reason: '' })
  const [coupons,setCoupons]=useState<Coupon[]>([]); const [showCoupons,setShowCoupons]=useState(false); const [couponForm,setCouponForm]=useState({code:'',description:'',discountType:'percentage' as 'percentage'|'fixed',discountValue:'10',minimumOrder:'0',maximumDiscount:'',endsAt:'',usageLimit:'',usageLimitPerCustomer:'1'})

  const load = useCallback(async () => { setLoading(true); setError(''); try { const [list, metrics,couponList] = await Promise.all([apiGet<Customer[]>('/api/customers', { limit: 2000 }), apiGet<Summary>('/api/customers/summary'),apiGet<Coupon[]>('/api/customers/coupons')]); setCustomers(list); setSummary(metrics);setCoupons(couponList) } catch (err) { setError(errorMessage(err, 'Não foi possível carregar os clientes.')) } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const filtered = useMemo(() => customers.filter(c => { const term = search.trim().toLocaleLowerCase('pt-BR'); return (segment === 'all' || c.segment === segment) && (!term || c.name.toLocaleLowerCase('pt-BR').includes(term) || c.phone.includes(term) || c.email?.toLocaleLowerCase('pt-BR').includes(term)) }), [customers, search, segment])

  async function openDetail(customer: Customer) { setError(''); try { setSelected(await apiGet<CustomerDetail>(`/api/customers/${customer.id}`)) } catch (err) { setError(errorMessage(err)) } }
  function openCreate() { setEditing(null); setForm(emptyForm); setShowForm(true) }
  function openEdit(customer: CustomerDetail) { setEditing(customer); setForm({ name: customer.name, phone: customer.phone, email: customer.email || '', address: customer.address || '', neighborhood: customer.neighborhood || '', city: customer.city || '', state: customer.state || '', zipCode: customer.zipCode || '', notes: customer.notes || '', birthday: customer.birthday?.slice(0, 10) || '', marketingConsent: customer.marketingConsent }); setShowForm(true) }
  async function saveCustomer(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const payload = { ...form, email: form.email || null, birthday: form.birthday || null }; const saved = editing ? await apiPut<Customer>(`/api/customers/${editing.id}`, payload) : await apiPost<Customer>('/api/customers', payload); setShowForm(false); setNotice(editing ? 'Cliente atualizado.' : 'Cliente cadastrado.'); await load(); if (editing) await openDetail({ ...editing, ...saved, segment: editing.segment }) } catch (err) { setError(errorMessage(err, 'Não foi possível salvar o cliente.')) } finally { setSaving(false) } }
  async function saveBenefit(event: FormEvent) { event.preventDefault(); if (!selected) return; setSaving(true); setError(''); try { await apiPost(`/api/customers/${selected.id}/benefits`, { pointsDelta: Number(benefit.pointsDelta || 0), cashbackDelta: Number(benefit.cashbackDelta || 0), reason: benefit.reason }); setShowBenefit(false); setBenefit({ pointsDelta: '', cashbackDelta: '', reason: '' }); setNotice('Benefício atualizado com histórico.'); await Promise.all([load(), openDetail(selected)]) } catch (err) { setError(errorMessage(err, 'Não foi possível atualizar o benefício.')) } finally { setSaving(false) } }
  async function saveCoupon(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{await apiPost('/api/customers/coupons',{code:couponForm.code,description:couponForm.description||null,discountType:couponForm.discountType,discountValue:Number(couponForm.discountValue),minimumOrder:Number(couponForm.minimumOrder||0),maximumDiscount:couponForm.maximumDiscount?Number(couponForm.maximumDiscount):null,startsAt:new Date().toISOString(),endsAt:couponForm.endsAt?new Date(`${couponForm.endsAt}T23:59:59`).toISOString():null,usageLimit:couponForm.usageLimit?Number(couponForm.usageLimit):null,usageLimitPerCustomer:Number(couponForm.usageLimitPerCustomer||1),active:true});setCouponForm({code:'',description:'',discountType:'percentage',discountValue:'10',minimumOrder:'0',maximumDiscount:'',endsAt:'',usageLimit:'',usageLimitPerCustomer:'1'});setNotice('Cupom criado e disponível no PDV e cardápio digital.');await load()}catch(err){setError(errorMessage(err,'Não foi possível criar o cupom.'))}finally{setSaving(false)}}
  async function toggleCoupon(coupon:Coupon){setSaving(true);try{await apiPut(`/api/customers/coupons/${coupon.id}`,{code:coupon.code,description:coupon.description||null,discountType:coupon.discountType,discountValue:Number(coupon.discountValue),minimumOrder:Number(coupon.minimumOrder),maximumDiscount:coupon.maximumDiscount==null?null:Number(coupon.maximumDiscount),startsAt:coupon.startsAt,endsAt:coupon.endsAt||null,usageLimit:coupon.usageLimit??null,usageLimitPerCustomer:coupon.usageLimitPerCustomer,active:!coupon.active});await load()}catch(err){setError(errorMessage(err))}finally{setSaving(false)}}

  return <div className="mx-auto flex w-full max-w-[1600px] flex-col gap-5">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="mb-1 text-xs font-semibold tracking-[.14em] text-accent uppercase">Relacionamento</p><h2 className="font-display text-3xl text-plum">Clientes</h2><p className="mt-1 text-sm text-slate">Conheça, segmente e fidelize quem compra com você.</p></div>{canManage && <div className="flex gap-2"><button onClick={()=>setShowCoupons(true)} className="inline-flex h-11 items-center gap-2 rounded-lg border border-brand bg-surface px-4 text-sm font-semibold text-accent"><TicketPercent className="h-4 w-4"/>Cupons</button><button onClick={openCreate} className="inline-flex h-11 items-center gap-2 rounded-lg bg-plum px-5 text-sm font-semibold text-cream"><UserPlus className="h-4 w-4" />Novo cliente</button></div>}</header>
    {error && <div role="alert" className="flex items-center justify-between rounded-lg border border-bad/25 bg-bad-soft px-4 py-3 text-sm text-bad"><span>{error}</span><button onClick={() => setError('')}><X className="h-4 w-4" /></button></div>}{notice && <div role="status" className="flex items-center gap-2 rounded-lg border border-good/25 bg-good-soft px-4 py-3 text-sm text-good"><CheckCircle2 className="h-4 w-4" />{notice}</div>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi icon={Users} label="Clientes cadastrados" value={String(summary?.total ?? 0)} detail={`${summary?.active ?? 0} ativos em 60 dias`} tone="brand" /><Kpi icon={UserPlus} label="Novos" value={String(summary?.segmentCounts.new ?? 0)} detail="Primeira compra recente" tone="good" /><Kpi icon={Heart} label="Recorrência" value={`${(summary?.recurrence ?? 0).toFixed(1)}%`} detail="Com 2 ou mais pedidos" tone="brand" /><Kpi icon={ShoppingBag} label="Ticket médio" value={money.format(summary?.averageTicket ?? 0)} detail="Histórico dos clientes" tone="warn" /><Kpi icon={Coins} label="Cashback em carteira" value={money.format(summary?.cashbackOutstanding ?? 0)} detail="Saldo disponível" tone="good" /></section>
    <div className="grid items-start gap-4 2xl:grid-cols-[minmax(0,1fr)_370px]">
      <section className="overflow-hidden rounded-card border border-line bg-surface shadow-sm"><div className="flex flex-col gap-3 border-b border-line p-3 lg:flex-row"><label className="relative flex-1"><Search className="absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-slate" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar por nome, telefone ou e-mail" className="h-10 w-full rounded-lg border border-line bg-canvas pr-3 pl-10 text-sm outline-none focus:border-brand" /></label><select value={segment} onChange={e => setSegment(e.target.value as Segment)} className="h-10 rounded-lg border border-line bg-surface px-3 text-sm">{(['all','champions','loyal','new','risk','inactive','regular'] as Segment[]).map(key => <option key={key} value={key}>{labels[key]}{key !== 'all' ? ` (${summary?.segmentCounts[key] ?? 0})` : ''}</option>)}</select></div>
        {loading ? <div className="flex min-h-96 items-center justify-center gap-2 text-sm text-slate"><Loader2 className="h-4 w-4 animate-spin" />Carregando...</div> : filtered.length === 0 ? <div className="px-6 py-20 text-center"><Users className="mx-auto h-9 w-9 text-slate/30" /><p className="mt-3 font-semibold">Nenhum cliente encontrado</p><p className="mt-1 text-sm text-slate">Ajuste a busca ou cadastre o primeiro cliente.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-canvas text-xs text-slate"><tr><th className="px-4 py-3">Cliente</th><th className="px-3 py-3">Última compra</th><th className="px-3 py-3 text-right">Pedidos</th><th className="px-3 py-3 text-right">Total gasto</th><th className="px-3 py-3 text-right">Ticket médio</th><th className="px-3 py-3">Segmento</th><th className="px-4 py-3"></th></tr></thead><tbody>{filtered.map(c => <tr key={c.id} onClick={() => void openDetail(c)} className={`cursor-pointer border-t border-line hover:bg-canvas/70 ${selected?.id === c.id ? 'bg-brand-soft/50' : ''}`}><td className="px-4 py-3"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-plum text-xs font-bold text-cream">{c.name.split(' ').slice(0,2).map(p => p[0]).join('').toUpperCase()}</span><div><strong>{c.name}</strong><p className="text-xs text-slate">{c.phone}</p></div></div></td><td className="px-3 py-3 text-slate">{c.lastOrderAt ? new Date(c.lastOrderAt).toLocaleDateString('pt-BR') : 'Nunca comprou'}</td><td className="px-3 py-3 text-right font-semibold">{c.totalOrders}</td><td className="px-3 py-3 text-right font-semibold">{money.format(Number(c.ltv))}</td><td className="px-3 py-3 text-right text-slate">{money.format(c.totalOrders ? Number(c.ltv)/c.totalOrders : 0)}</td><td className="px-3 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tones[c.segment]}`}>{labels[c.segment]}</span></td><td className="px-4 py-3"><ChevronRight className="h-4 w-4 text-slate" /></td></tr>)}</tbody></table></div>}
      </section>
      <aside className="rounded-card border border-line bg-surface shadow-sm">{selected ? <CustomerProfile customer={selected} canManage={canManage} onEdit={() => openEdit(selected)} onBenefit={() => setShowBenefit(true)} /> : <div className="px-6 py-20 text-center"><Sparkles className="mx-auto h-9 w-9 text-accent/40" /><p className="mt-3 font-semibold text-ink">Selecione um cliente</p><p className="mt-1 text-sm text-slate">Veja perfil, pedidos e endereços.</p></div>}</aside>
    </div>
    {showForm && <Modal title={editing ? 'Editar cliente' : 'Novo cliente'} subtitle="Cadastro simples, com informações opcionais para relacionamento." onClose={() => setShowForm(false)}><form onSubmit={saveCustomer} className="grid gap-4 sm:grid-cols-2"><Field label="Nome" wide><input required value={form.name} onChange={e => setForm(v => ({...v,name:e.target.value}))} className={fieldClass}/></Field><Field label="Telefone"><input required inputMode="tel" value={form.phone} onChange={e => setForm(v => ({...v,phone:e.target.value}))} className={fieldClass}/></Field><Field label="E-mail"><input type="email" value={form.email} onChange={e => setForm(v => ({...v,email:e.target.value}))} className={fieldClass}/></Field><Field label="Aniversário"><input type="date" value={form.birthday} onChange={e => setForm(v => ({...v,birthday:e.target.value}))} className={fieldClass}/></Field><Field label="Endereço" wide><input value={form.address} onChange={e => setForm(v => ({...v,address:e.target.value}))} className={fieldClass}/></Field><Field label="Bairro"><input value={form.neighborhood} onChange={e => setForm(v => ({...v,neighborhood:e.target.value}))} className={fieldClass}/></Field><Field label="Cidade"><input value={form.city} onChange={e => setForm(v => ({...v,city:e.target.value}))} className={fieldClass}/></Field><Field label="UF"><input maxLength={2} value={form.state} onChange={e => setForm(v => ({...v,state:e.target.value.toUpperCase()}))} className={fieldClass}/></Field><Field label="CEP"><input value={form.zipCode} onChange={e => setForm(v => ({...v,zipCode:e.target.value}))} className={fieldClass}/></Field><Field label="Observações internas" wide><textarea rows={3} value={form.notes} onChange={e => setForm(v => ({...v,notes:e.target.value}))} className={`${fieldClass} h-auto py-3`}/></Field><label className="flex items-start gap-2 text-sm text-ink sm:col-span-2"><input type="checkbox" checked={form.marketingConsent} onChange={e => setForm(v => ({...v,marketingConsent:e.target.checked}))}/><span><strong>Autoriza comunicações promocionais</strong><small className="block text-slate">Registre apenas quando o cliente concordar.</small></span></label><Actions saving={saving} onClose={() => setShowForm(false)} label="Salvar cliente" /></form></Modal>}
    {showBenefit && selected && <Modal title="Ajustar benefícios" subtitle={`${selected.name} · ${selected.loyaltyPoints} pontos · ${money.format(Number(selected.cashbackBalance))}`} onClose={() => setShowBenefit(false)}><form onSubmit={saveBenefit} className="grid gap-4 sm:grid-cols-2"><Field label="Pontos (+ ou -)"><input type="number" step="1" value={benefit.pointsDelta} onChange={e => setBenefit(v => ({...v,pointsDelta:e.target.value}))} placeholder="Ex.: 50 ou -20" className={fieldClass}/></Field><Field label="Cashback (+ ou -)"><input type="number" step="0.01" value={benefit.cashbackDelta} onChange={e => setBenefit(v => ({...v,cashbackDelta:e.target.value}))} placeholder="Ex.: 5,00 ou -2,00" className={fieldClass}/></Field><Field label="Motivo" wide><textarea required minLength={3} rows={3} value={benefit.reason} onChange={e => setBenefit(v => ({...v,reason:e.target.value}))} placeholder="Ex.: bônus de aniversário ou resgate no pedido" className={`${fieldClass} h-auto py-3`}/></Field><Actions saving={saving} onClose={() => setShowBenefit(false)} label="Registrar ajuste" /></form></Modal>}
    {showCoupons&&<Modal title="Cupons promocionais" subtitle="As mesmas regras valem no PDV e no cardápio digital." onClose={()=>setShowCoupons(false)}><div className="mb-5 space-y-2">{coupons.map(c=><div key={c.id} className="flex items-center gap-3 rounded-xl border border-line p-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-brand-soft text-accent"><TicketPercent className="h-4 w-4"/></span><div className="min-w-0 flex-1"><strong className="font-mono text-ink">{c.code}</strong><p className="text-xs text-slate">{c.discountType==='percentage'?`${Number(c.discountValue)}%`:money.format(Number(c.discountValue))} · mínimo {money.format(Number(c.minimumOrder))} · {c.usageCount} uso(s)</p></div><button disabled={saving} onClick={()=>void toggleCoupon(c)} className={`rounded-full px-3 py-1 text-xs font-bold ${c.active?'bg-good-soft text-good':'bg-slate/10 text-slate'}`}>{c.active?'Ativo':'Pausado'}</button></div>)}{!coupons.length&&<p className="rounded-xl bg-canvas p-4 text-center text-sm text-slate">Nenhum cupom criado.</p>}</div><form onSubmit={saveCoupon} className="grid gap-3 border-t border-line pt-5 sm:grid-cols-2"><Field label="Código"><input required minLength={3} value={couponForm.code} onChange={e=>setCouponForm(v=>({...v,code:e.target.value.toUpperCase()}))} placeholder="BEMVINDO10" className={fieldClass}/></Field><Field label="Descrição"><input value={couponForm.description} onChange={e=>setCouponForm(v=>({...v,description:e.target.value}))} className={fieldClass}/></Field><Field label="Tipo"><select value={couponForm.discountType} onChange={e=>setCouponForm(v=>({...v,discountType:e.target.value as 'percentage'|'fixed'}))} className={fieldClass}><option value="percentage">Percentual</option><option value="fixed">Valor fixo</option></select></Field><Field label={couponForm.discountType==='percentage'?'Desconto (%)':'Desconto (R$)'}><input required type="number" min="0.01" step="0.01" value={couponForm.discountValue} onChange={e=>setCouponForm(v=>({...v,discountValue:e.target.value}))} className={fieldClass}/></Field><Field label="Pedido mínimo"><input type="number" min="0" step="0.01" value={couponForm.minimumOrder} onChange={e=>setCouponForm(v=>({...v,minimumOrder:e.target.value}))} className={fieldClass}/></Field><Field label="Desconto máximo"><input type="number" min="0.01" step="0.01" value={couponForm.maximumDiscount} onChange={e=>setCouponForm(v=>({...v,maximumDiscount:e.target.value}))} placeholder="Opcional" className={fieldClass}/></Field><Field label="Validade"><input type="date" value={couponForm.endsAt} onChange={e=>setCouponForm(v=>({...v,endsAt:e.target.value}))} className={fieldClass}/></Field><Field label="Limite total"><input type="number" min="1" value={couponForm.usageLimit} onChange={e=>setCouponForm(v=>({...v,usageLimit:e.target.value}))} placeholder="Sem limite" className={fieldClass}/></Field><Actions saving={saving} onClose={()=>setShowCoupons(false)} label="Criar cupom"/></form></Modal>}
  </div>
}

function CustomerProfile({customer,canManage,onEdit,onBenefit}:{customer:CustomerDetail;canManage:boolean;onEdit:()=>void;onBenefit:()=>void}) { return <><div className="border-b border-line p-5"><div className="flex items-start gap-3"><span className="grid h-14 w-14 place-items-center rounded-full bg-plum text-lg font-bold text-cream">{customer.name.split(' ').slice(0,2).map(p=>p[0]).join('').toUpperCase()}</span><div className="min-w-0 flex-1"><h3 className="truncate font-display text-xl text-plum">{customer.name}</h3><span className={`mt-1 inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${tones[customer.segment]}`}>{labels[customer.segment]}</span></div>{canManage&&<button onClick={onEdit} title="Editar cliente"><Edit3 className="h-4 w-4 text-slate"/></button>}</div><div className="mt-4 space-y-2 text-sm text-slate"><p className="flex gap-2"><Phone className="h-4 w-4"/>{customer.phone}</p>{customer.address&&<p className="flex gap-2"><MapPin className="h-4 w-4 shrink-0"/>{[customer.address,customer.neighborhood,customer.city].filter(Boolean).join(' · ')}</p>}{customer.birthday&&<p className="flex gap-2"><Cake className="h-4 w-4"/>{new Date(customer.birthday).toLocaleDateString('pt-BR',{timeZone:'UTC'})}</p>}</div></div><div className="grid grid-cols-2 gap-px bg-line"><div className="bg-surface p-4 text-center"><Coins className="mx-auto h-5 w-5 text-accent"/><strong className="mt-1 block text-xl text-plum">{customer.loyaltyPoints}</strong><span className="text-xs text-slate">pontos</span></div><div className="bg-surface p-4 text-center"><Gift className="mx-auto h-5 w-5 text-good"/><strong className="mt-1 block text-xl text-plum">{money.format(Number(customer.cashbackBalance))}</strong><span className="text-xs text-slate">cashback</span></div></div>{canManage&&<div className="border-b border-line p-4"><button onClick={onBenefit} className="inline-flex h-10 w-full items-center justify-center gap-2 rounded-lg bg-brand px-3 text-sm font-bold text-brand-ink"><Gift className="h-4 w-4"/>Ajustar benefícios</button></div>}<div className="p-4"><h4 className="font-semibold text-ink">Últimos pedidos</h4><div className="mt-2 divide-y divide-line">{customer.orders.slice(0,5).map(order=><div key={order.id} className="flex items-center justify-between py-2 text-sm"><div><strong>#{order.orderNumber}</strong><p className="text-xs text-slate">{new Date(order.createdAt).toLocaleDateString('pt-BR')}</p></div><span className="font-semibold">{money.format(Number(order.totalAmount))}</span></div>)}{!customer.orders.length&&<p className="py-4 text-sm text-slate">Nenhum pedido ainda.</p>}</div>{customer.notes&&<p className="mt-3 rounded-lg bg-canvas p-3 text-xs text-slate">{customer.notes}</p>}</div></> }
function Kpi({icon:Icon,label,value,detail,tone}:{icon:typeof Users;label:string;value:string;detail:string;tone:'brand'|'good'|'warn'}) { const style={brand:'bg-brand-soft text-accent',good:'bg-good-soft text-good',warn:'bg-warn-soft text-warn'}[tone]; return <article className="flex items-center gap-3 rounded-card border border-line bg-surface p-4 shadow-sm"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-full ${style}`}><Icon className="h-5 w-5"/></span><div className="min-w-0"><p className="truncate text-xs text-slate">{label}</p><strong className="block truncate text-xl text-plum">{value}</strong><p className="truncate text-xs text-slate">{detail}</p></div></article> }
function Modal({title,subtitle,onClose,children}:{title:string;subtitle:string;onClose:()=>void;children:ReactNode}) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/60 p-4"><div role="dialog" aria-modal="true" className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-card border border-line bg-surface p-5 shadow-xl"><div className="mb-5 flex justify-between"><div><h3 className="font-display text-2xl text-plum">{title}</h3><p className="text-sm text-slate">{subtitle}</p></div><button onClick={onClose}><X className="h-5 w-5"/></button></div>{children}</div></div> }
function Field({label,wide,children}:{label:string;wide?:boolean;children:ReactNode}) { return <label className={`flex flex-col gap-1.5 text-sm font-medium text-ink ${wide?'sm:col-span-2':''}`}>{label}{children}</label> }
function Actions({saving,onClose,label}:{saving:boolean;onClose:()=>void;label:string}) { return <div className="mt-2 flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={onClose} className="h-10 rounded-lg border border-line px-4 text-sm font-semibold">Cancelar</button><button disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-lg bg-plum px-4 text-sm font-semibold text-cream disabled:opacity-60">{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}{label}</button></div> }
